---
- name: Setup dotfiles
  file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: yes
      state: link
      with_items:
          - "{{ dotfiles }}"

- name: Change login shell to fish
  become: yes
  become_method: sudo
  user:
      name: "{{ ansible_user_id }}"
      shell: /usr/local/bin/fish
      state: present

